# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WelcomeKitExample' do
    use_frameworks!

    # Pods for WelcomeKitExample
    pod 'SnapKit'
    pod 'lottie-ios'
end

